import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy — Try Out',
  description: 'How Try Out collects, uses, and protects your personal information.',
};

const SECTIONS = [
  {
    title: '1. Information We Collect',
    content: [
      {
        subtitle: 'Account Information',
        text: 'When you sign in via Google OAuth, we receive your name, email address, and profile picture from Google. This information is stored securely in our database to identify your account and personalize your experience.',
      },
      {
        subtitle: 'Usage Data',
        text: 'We collect information about how you interact with the Service, including the prompts you submit, the thumbnails you generate, the styles and aspect ratios you select, and your credit usage history.',
      },
      {
        subtitle: 'Payment Information',
        text: 'We use Polar as our payment processor. We do not store your credit card details on our servers. Polar collects and handles all payment information in accordance with PCI-DSS standards. We only retain your credit balance and transaction history.',
      },
      {
        subtitle: 'Uploaded Files',
        text: 'If you upload reference images to guide thumbnail generation, those files are stored temporarily in Supabase Storage and associated with your account. You may delete them at any time.',
      },
    ],
  },
  {
    title: '2. How We Use Your Information',
    content: [
      {
        subtitle: 'Service Delivery',
        text: 'We use your information to operate Try Out — to authenticate you, process your thumbnail generation requests, track your credit balance, and display your generation history.',
      },
      {
        subtitle: 'Communication',
        text: 'We may use your email address to send transactional messages such as payment receipts, credit balance alerts, or important service updates. We do not send unsolicited marketing emails.',
      },
      {
        subtitle: 'Improvement',
        text: 'Aggregated and anonymized usage data helps us improve the quality of our AI prompts, generation speed, and overall product experience. We do not sell or share individual user data with third parties for advertising.',
      },
    ],
  },
  {
    title: '3. Data Sharing',
    content: [
      {
        subtitle: 'Third-Party Service Providers',
        text: 'We share data only with the vendors necessary to operate the Service: Supabase (authentication and database), Polar (payment processing), and Google (AI image generation via Gemini API and OAuth). Each provider is contractually bound to protect your data.',
      },
      {
        subtitle: 'Legal Requirements',
        text: 'We may disclose your information if required by law, court order, or governmental authority, or if we believe in good faith that such disclosure is necessary to protect our rights or prevent harm.',
      },
      {
        subtitle: 'No Sale of Data',
        text: 'We do not sell, rent, or trade your personal information to third parties for their marketing purposes under any circumstances.',
      },
    ],
  },
  {
    title: '4. Data Retention',
    content: [
      {
        subtitle: 'Account Data',
        text: 'Your account information and generation history are retained for as long as your account is active. If you request account deletion, we will remove your personal data within 30 days, except where retention is required by law.',
      },
      {
        subtitle: 'Generated Images',
        text: 'Thumbnail images generated by the Service are stored on Supabase Storage and linked to your account. You can delete individual thumbnails at any time from the dashboard. All stored images are deleted upon account deletion.',
      },
    ],
  },
  {
    title: '5. Security',
    content: [
      {
        subtitle: 'Protection Measures',
        text: 'We implement industry-standard security measures including HTTPS encryption for all data in transit, encrypted storage for sensitive fields, and access controls that limit which personnel can access production data.',
      },
      {
        subtitle: 'No Guarantee',
        text: 'While we take all reasonable precautions, no method of transmission over the internet or electronic storage is 100% secure. We cannot guarantee absolute security and encourage you to use a strong, unique password for your Google account.',
      },
    ],
  },
  {
    title: '6. Your Rights',
    content: [
      {
        subtitle: 'Access & Portability',
        text: 'You may request a copy of the personal data we hold about you at any time by contacting us at the email address below.',
      },
      {
        subtitle: 'Deletion',
        text: 'You have the right to request deletion of your account and associated personal data. Submit your request via email and we will process it within 30 days.',
      },
      {
        subtitle: 'Correction',
        text: 'If any information we hold about you is inaccurate, you may request a correction by contacting our support team.',
      },
    ],
  },
  {
    title: '7. Cookies',
    content: [
      {
        subtitle: 'Session Cookies',
        text: 'We use session cookies to keep you authenticated between page visits. These cookies are essential for the Service to function and are deleted when you log out or close your browser.',
      },
      {
        subtitle: 'No Tracking Cookies',
        text: 'We do not use third-party tracking, analytics, or advertising cookies. We do not participate in cross-site user tracking.',
      },
    ],
  },
  {
    title: '8. Children\'s Privacy',
    content: [
      {
        subtitle: 'Age Restriction',
        text: 'Try Out is not intended for children under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact us and we will promptly delete it.',
      },
    ],
  },
  {
    title: '9. Changes to This Policy',
    content: [
      {
        subtitle: 'Notification',
        text: 'We may update this Privacy Policy from time to time. When we do, we will revise the "Last Updated" date at the top of the page. If the changes are material, we will notify you by email or by displaying a prominent notice on the Service.',
      },
    ],
  },
  {
    title: '10. Contact Us',
    content: [
      {
        subtitle: 'Questions',
        text: 'If you have any questions or concerns about this Privacy Policy or how we handle your data, please contact us at: privacy@tryout.app',
      },
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <main style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #0a0a14 0%, #0d0a1a 40%, #080d14 100%)',
      position: 'relative',
      overflowX: 'hidden',
    }}>
      {/* Subtle mesh gradient */}
      <div style={{ position: 'fixed', inset: 0, zIndex: 0, pointerEvents: 'none' }}>
        <div style={{ position: 'absolute', width: 600, height: 600, borderRadius: '50%', background: 'radial-gradient(circle, rgba(99,102,241,0.06) 0%, transparent 70%)', top: -120, left: -80 }} />
        <div style={{ position: 'absolute', width: 500, height: 500, borderRadius: '50%', background: 'radial-gradient(circle, rgba(168,85,247,0.05) 0%, transparent 70%)', top: '30%', right: -100 }} />
        <div style={{ position: 'absolute', width: 400, height: 400, borderRadius: '50%', background: 'radial-gradient(circle, rgba(34,211,238,0.04) 0%, transparent 70%)', bottom: 0, left: '40%' }} />
      </div>

      {/* Content */}
      <div style={{ position: 'relative', zIndex: 1, maxWidth: 780, margin: '0 auto', padding: '48px 24px 96px' }}>

        {/* Back navigation */}
        <Link
          href="/"
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            color: 'rgba(255,255,255,0.45)', fontSize: 13, fontWeight: 500,
            textDecoration: 'none', marginBottom: 48,
            transition: 'color 0.2s',
          }}
        >
          <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
            <path d="M10 3L5 8L10 13" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Back to Home
        </Link>

        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '4px 12px', borderRadius: 20,
            background: 'rgba(168,85,247,0.10)',
            border: '1px solid rgba(168,85,247,0.20)',
            marginBottom: 16,
          }}>
            <svg width="12" height="12" viewBox="0 0 16 16" fill="none">
              <path d="M8 1L10.5 6L16 6.5L12 10.5L13 16L8 13L3 16L4 10.5L0 6.5L5.5 6L8 1Z" fill="rgba(168,85,247,0.8)"/>
            </svg>
            <span style={{ color: 'rgba(168,85,247,0.8)', fontSize: 11, fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase' }}>
              Legal
            </span>
          </div>
          <h1 style={{
            color: '#fff', fontSize: 'clamp(28px, 5vw, 42px)',
            fontWeight: 700, margin: '0 0 12px',
            letterSpacing: '-0.5px', lineHeight: 1.2,
          }}>
            Privacy Policy
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.40)', fontSize: 14, margin: 0 }}>
            Last Updated: April 12, 2025
          </p>
          <p style={{ color: 'rgba(255,255,255,0.55)', fontSize: 15, margin: '16px 0 0', lineHeight: 1.7 }}>
            Try Out (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy. This policy explains what information we collect when you use our AI-powered YouTube thumbnail generation service, how we use it, and your rights with respect to that information.
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {SECTIONS.map((section, si) => (
            <div
              key={si}
              style={{
                borderRadius: 16,
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid rgba(255,255,255,0.07)',
                overflow: 'hidden',
                transition: 'border-color 0.2s',
              }}
            >
              {/* Section title */}
              <div style={{
                padding: '20px 28px 16px',
                borderBottom: '1px solid rgba(255,255,255,0.05)',
              }}>
                <h2 style={{
                  color: 'rgba(168,85,247,0.85)',
                  fontSize: 15, fontWeight: 700,
                  margin: 0, letterSpacing: '-0.2px',
                }}>
                  {section.title}
                </h2>
              </div>

              {/* Subsections */}
              <div style={{ padding: '20px 28px', display: 'flex', flexDirection: 'column', gap: 18 }}>
                {section.content.map((item, ii) => (
                  <div key={ii}>
                    <h3 style={{
                      color: 'rgba(255,255,255,0.80)',
                      fontSize: 13, fontWeight: 600,
                      margin: '0 0 6px', letterSpacing: '0.01em',
                    }}>
                      {item.subtitle}
                    </h3>
                    <p style={{
                      color: 'rgba(255,255,255,0.50)',
                      fontSize: 14, lineHeight: 1.75,
                      margin: 0,
                    }}>
                      {item.text}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer link */}
        <div style={{ marginTop: 48, paddingTop: 32, borderTop: '1px solid rgba(255,255,255,0.06)', textAlign: 'center' }}>
          <p style={{ color: 'rgba(255,255,255,0.25)', fontSize: 13, margin: '0 0 12px' }}>
            Also see our
          </p>
          <Link
            href="/terms-of-service"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              padding: '8px 18px', borderRadius: 10,
              background: 'rgba(168,85,247,0.08)',
              border: '1px solid rgba(168,85,247,0.18)',
              color: 'rgba(168,85,247,0.75)', fontSize: 13, fontWeight: 600,
              textDecoration: 'none', transition: 'all 0.2s',
            }}
          >
            Terms of Service
            <svg width="12" height="12" viewBox="0 0 16 16" fill="none">
              <path d="M6 3L11 8L6 13" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </Link>
        </div>
      </div>
    </main>
  );
}
